import type { SkillMarketplaceEntry } from '@catbuddy/shared'

/** Curated built-in skills — featured entries are practical and require little setup. */
export const SKILL_MARKETPLACE: SkillMarketplaceEntry[] = [
  {
    id: 'weather',
    name: '天气查询',
    skillName: 'weather',
    emoji: '🌤️',
    featured: true,
    description: '查当前天气与预报，无需 API Key，适合出行、日程和生活类问答。',
    category: '一键可用',
  },
  {
    id: 'long-goal',
    name: '长期目标',
    skillName: 'long-goal',
    emoji: '🎯',
    featured: true,
    description: '拆解长期任务、分阶段推进、复杂项目前先调研再执行。',
    category: '一键可用',
  },
  {
    id: 'cron',
    name: '定时提醒',
    skillName: 'cron',
    emoji: '⏰',
    featured: true,
    description: '设置一次性提醒和周期性任务，真正推送通知，而不是只写入记忆。',
    category: '一键可用',
  },
  {
    id: 'image-generation',
    name: '图像生成',
    skillName: 'image-generation',
    emoji: '🎨',
    featured: true,
    description: '根据描述生成或迭代图片，适合头像、海报、插图和创意草稿。',
    category: '需启用工具',
    setupNote: '需在设置中启用图像生成工具后才能调用。',
  },
  {
    id: 'github',
    name: 'GitHub',
    skillName: 'github',
    emoji: '🐙',
    description: '用 gh 管理仓库、Issue、PR 和 CI，查询提交与流水线状态。',
    category: '需本机配置',
    setupNote: '需安装 GitHub CLI，并完成 gh auth login。',
  },
  {
    id: 'summarize',
    name: '链接摘要',
    skillName: 'summarize',
    emoji: '🧾',
    description: '总结网页、播客、本地文件，适合“帮我概括这个链接/视频”。',
    category: '需本机配置',
    setupNote: '需安装 summarize CLI 后使用。',
  },
  {
    id: 'tmux',
    name: 'tmux 终端',
    skillName: 'tmux',
    emoji: '🖥️',
    description: '远程查看与控制 tmux 会话，适合长时间运行的后台命令。',
    category: '需本机配置',
    setupNote: '需系统已安装 tmux。Windows 环境建议通过 WSL 使用。',
  },
]
