import type { SkillMarketplaceEntry } from '@catbuddy/shared'

/** Curated built-in skills — featured entries appear first in the marketplace UI. */
export const SKILL_MARKETPLACE: SkillMarketplaceEntry[] = [
  {
    id: 'cron',
    name: '定时提醒',
    skillName: 'cron',
    emoji: '⏰',
    featured: true,
    description: '用 cron 工具设置一次性或周期性提醒、后台任务，真正推送通知（不要只写进 MEMORY）。',
    category: '日常',
  },
  {
    id: 'github',
    name: 'GitHub',
    skillName: 'github',
    emoji: '🐙',
    featured: true,
    description: '用 gh 管理仓库、Issue、PR 和 CI，查提交与流水线状态。',
    category: '开发',
    setupNote: '需安装 gh 并完成 gh auth login。',
  },
  {
    id: 'weather',
    name: '天气查询',
    skillName: 'weather',
    emoji: '🌤️',
    featured: true,
    description: '查当前天气与预报，无需 API Key（wttr.in / Open-Meteo）。',
    category: '生活',
  },
  {
    id: 'summarize',
    name: '链接摘要',
    skillName: 'summarize',
    emoji: '🧾',
    featured: true,
    description: '总结网页、播客、本地文件；适合「帮我概括这个链接/视频」。',
    category: '效率',
    setupNote: '需安装 summarize CLI（见 SKILL.md）。',
  },
  {
    id: 'image-generation',
    name: '图像生成',
    skillName: 'image-generation',
    emoji: '🎨',
    featured: true,
    description: '根据描述生成或迭代修改图片（generate_image 工具）。',
    category: '创作',
    setupNote: '请在设置中启用图像生成相关工具。',
  },
  {
    id: 'tmux',
    name: 'tmux 终端',
    skillName: 'tmux',
    emoji: '🖥️',
    description: '远程查看与控制 tmux 会话，适合长时间跑在后台的命令。',
    category: '开发',
    setupNote: '需系统已安装 tmux。',
  },
  {
    id: 'long-goal',
    name: '长期目标',
    skillName: 'long-goal',
    emoji: '🎯',
    description: '拆解长期任务、分阶段推进、复杂项目前先调研再动手。',
    category: '效率',
  },
]
