import type { McpServerConfig, TokenUsage, FileEditEvent, DiagramUiEvent } from './agent-types.js'

export type Role = "user" | "assistant" | "tool" | "system";

/** "trace" rows are intermediate agent breadcrumbs (tool-call hints,
 * progress pings) that should not be rendered as conversational replies. */
export type MessageKind = "message" | "trace";

/** One image attached to a UIMessage.
 *
 * ``url`` can arrive in three different shapes, which the bubble renders
 * identically:
 * - A ``data:image/...;base64,...`` URL generated by the Composer for the
 *   optimistic preview of an in-flight user turn. Self-contained, no
 *   lifecycle.
 * - A signed ``/api/media/...`` URL attached to a historical user turn by
 *   the backend on session replay. Safe to drop into an ``<img src>``.
 * - Absent. The backend couldn't resolve a stored path (file moved,
 *   deleted, or pre-media-persistence session). The bubble shows a
 *   placeholder tile with ``name`` as the label.
 */
export interface UIImage {
  url?: string;
  name?: string;
}

export type UIMediaKind = "image" | "video" | "file";

export interface UIMediaAttachment {
  kind: UIMediaKind;
  url?: string;
  name?: string;
}

export interface UIMessage {
  id: string;
  role: Role;
  content: string;
  kind?: MessageKind;
  isStreaming?: boolean;
  createdAt: number;
  /** For trace rows: each individual hint line, so consecutive hints can
   * render as a single collapsible group. */
  traces?: string[];
  /** Per call_id merged tool progress (start → end/error on same row). */
  toolProgress?: Record<string, ToolProgressEvent>;
  /** Activity rows: explicit file edits emitted by edit tools. */
  fileEdits?: UIFileEdit[];
  /** Activity rows created during the same agent phase share one collapsible block. */
  activitySegmentId?: string;
  /** User turn: optimistic blob URLs for preview. Replay: placeholder chips. */
  images?: UIImage[];
  /** Signed or local UI-renderable media attachments. */
  media?: UIMediaAttachment[];
  /** Assistant turn: accumulated model reasoning / thinking text. Built up
   * incrementally from ``reasoning_delta`` frames; finalized when
   * ``reasoning_end`` arrives. */
  reasoning?: string;
  /** True while ``reasoning_delta`` frames are still arriving for this turn.
   * Drives the shimmer header on ``ReasoningBubble``. */
  reasoningStreaming?: boolean;
  /** End-to-end wall time for this assistant turn (persisted ``latency_ms`` / ``turn_end``). */
  latencyMs?: number;
  /** Aggregated LLM token usage for this assistant turn (``turn_end``). */
  tokenUsage?: TokenUsage;
}

/** Structured UI blob on ``progress`` WS frames; channels may add more ``kind`` values later. */
export interface AgentUIBlob {
  kind: string;
  data?: unknown;
}

/** WebSocket snapshot for sustained goals (`goal_state` events; keyed by ``chat_id``). */
export interface GoalStateWsPayload {
  active: boolean;
  ui_summary?: string;
  objective?: string;
}

export interface ToolProgressEvent {
  version?: number;
  phase?: "start" | "end" | "error" | string;
  call_id?: string;
  name?: string;
  arguments?: unknown;
  /** Short preview for completed tool (desktop IPC). */
  detail?: string;
  durationMs?: number;
  result?: unknown;
  error?: unknown;
  files?: unknown[];
  embeds?: unknown[];
}

/**
 * File edit event from desktop IPC.
 *
 * Fields use snake_case to match the desktop wire protocol (e.g. `call_id`,
 * `absolute_path`). Do not rename to camelCase without updating the desktop
 * IPC bridge and all transports.
 *
 * This is a re-export of the canonical `FileEditEvent` from agent-types.
 */
export type UIFileEdit = FileEditEvent;

/** Re-export of the canonical `DiagramUiEvent` from agent-types. */
export type UIDiagramEvent = DiagramUiEvent;

export interface ChatSummary {
  /** Server-side session key, e.g. ``websocket:abcd-...``. */
  key: string;
  /** Local channel + chat_id parts derived from ``key`` for convenience. */
  channel: string;
  chatId: string;
  createdAt: string | null;
  updatedAt: string | null;
  title?: string;
  preview: string;
  /** Logical workspace folder id grouping this chat history. */
  workspaceFolderId?: string | null;
  /** Display name for workspace grouping when folder registry is unavailable (Gateway/Web). */
  workspaceFolderName?: string | null;
}

export interface WorkspaceFolder {
  id: string;
  name: string;
  createdAt: string;
  /** Project root directory (e.g. selected folder A). */
  projectRoot: string;
  /** `.catbuddy` inside project root (memory/skills only). */
  catbuddyDir: string;
  /** App-owned project data dir: `~/.catbuddy/projects/<id>/` for sessions. */
  dataDir: string;
}

export type GatewayMode = 'nanobot' | 'gateway'

export interface BootstrapResponse {
  token: string;
  ws_path: string;
  expires_in: number;
  model_name?: string | null;
  /** When ``gateway``, the browser uses catbuddy Gateway (desktop runs Agent). */
  gateway_mode?: GatewayMode
  /** Desktop client connected (Web can run agent via gateway). */
  desktop_online?: boolean
  /** HTTP 401: Web must complete email login before bootstrap/API. */
  requires_auth?: boolean
}

export interface SettingsPayload {
  agent: {
    model: string;
    provider: string;
    resolved_provider: string | null;
    has_api_key: boolean;
  };
  providers: Array<{
    name: string;
    label: string;
    configured: boolean;
    api_key_required?: boolean;
    api_key_hint?: string | null;
    api_base?: string | null;
    default_api_base?: string | null;
  }>;
  web_search: {
    provider: string;
    api_key_hint?: string | null;
    base_url?: string | null;
    providers: Array<{
      name: string;
      label: string;
      credential: "none" | "api_key" | "base_url";
    }>;
  };
  runtime: {
    config_path: string;
  };
  requires_restart: boolean;
}

export interface SettingsUpdate {
  model?: string;
  provider?: string;
}

export interface ProviderSettingsUpdate {
  provider: string;
  apiKey?: string;
  apiBase?: string;
}

export interface WebSearchSettingsUpdate {
  provider: string;
  apiKey?: string;
  baseUrl?: string;
}

export interface McpSettingsServer {
  name: string;
  config: McpServerConfig;
  connected: boolean;
  toolCount: number;
  lastError?: string;
}

export interface McpSettingsPayload {
  servers: McpSettingsServer[];
}

export interface McpSettingsUpdateResult extends McpSettingsPayload {
  message: string;
}

export interface McpMarketplaceEntry {
  id: string;
  name: string;
  description: string;
  category: string;
  config: Record<string, McpServerConfig>;
  docsUrl?: string;
  requiresEnv?: string[];
  /** Extra setup steps shown in the marketplace card. */
  setupNote?: string;
  /** Remote HTTP MCP — cannot one-click connect until HTTP transport is supported. */
  pasteOnly?: boolean;
  /** JSON snippet to copy when pasteOnly is true. */
  pasteTemplate?: string;
}

/** Built-in skill curated for one-click install into workspace/skills/. */
export interface SkillMarketplaceEntry {
  id: string;
  name: string;
  description: string;
  category: string;
  /** Directory name under apps/desktop/skills and workspace/skills. */
  skillName: string;
  emoji?: string;
  /** Shown in the featured row at the top of the marketplace. */
  featured?: boolean;
  setupNote?: string;
}

export interface SkillInstallResult {
  message: string;
  skills: import('./agent-types.js').SkillInfo[];
  /** Skill is enabled; next agent turn rebuilds system prompt (no restart / new chat). */
  hotReload: boolean;
}

export interface SlashCommand {
  command: string;
  title: string;
  description: string;
  icon: string;
  argHint?: string;
}

export type ConnectionStatus =
  | "idle"
  | "connecting"
  | "open"
  | "reconnecting"
  | "closed"
  | "error";

// ── InboundEvent: sub-type groupings ──

/** Live delta/reasoning stream events from the agent. */
export type StreamEvents =
  | InboundDelta
  | InboundStreamEnd
  | InboundReasoningDelta
  | InboundReasoningEnd;

/** Session lifecycle events (turn boundaries, goal state). */
export type SessionEvents =
  | InboundTurnEnd
  | InboundGoalStatus
  | InboundGoalState
  | InboundSessionUpdated;

/** Agent output events (non-streamed messages, file edits, diagrams). */
export type AgentOutputEvents =
  | InboundAgentMessage
  | InboundFileEdit
  | InboundDiagramEvent;

// ── Individual event shapes ──

export type InboundMeta = { event: "ready"; chat_id: string; client_id: string }
  | { event: "attached"; chat_id: string };

/** User message injected from Web via Gateway (desktop did not send locally). */
export type InboundUserInput = { event: "user_inbound"; chat_id: string; text: string };

export type InboundAgentMessage = {
  event: "message";
  chat_id: string;
  text: string;
  reply_to?: string;
  media?: string[];
  media_urls?: Array<{ url: string; name?: string }>;
  tool_events?: ToolProgressEvent[];
  kind?: "tool_hint" | "progress" | "reasoning";
  latency_ms?: number;
  agent_ui?: AgentUIBlob;
};

export type InboundFileEdit = {
  event: "file_edit";
  chat_id: string;
  edits: UIFileEdit[];
};

export type InboundDiagramEvent = {
  event: "diagram_event";
  chat_id: string;
  diagram: UIDiagramEvent;
};

export type InboundDelta = {
  event: "delta";
  chat_id: string;
  text: string;
  stream_id?: string;
};

export type InboundStreamEnd = {
  event: "stream_end";
  chat_id: string;
  stream_id?: string;
};

export type InboundReasoningDelta = {
  event: "reasoning_delta";
  chat_id: string;
  text: string;
  stream_id?: string;
};

export type InboundReasoningEnd = {
  event: "reasoning_end";
  chat_id: string;
  stream_id?: string;
};

export type InboundRuntimeModel = {
  event: "runtime_model_updated";
  model_name: string;
  model_preset?: string | null;
};

export type InboundTurnEnd = {
  event: "turn_end";
  chat_id: string;
  latency_ms?: number;
  usage?: TokenUsage;
  tools_used?: string[];
  goal_state?: GoalStateWsPayload;
};

export type InboundGoalStatus = {
  event: "goal_status";
  chat_id: string;
  status: "running" | "idle";
  started_at?: number;
};

export type InboundGoalState = {
  event: "goal_state";
  chat_id: string;
  goal_state: GoalStateWsPayload;
};

export type InboundSessionUpdated = {
  event: "session_updated";
  chat_id: string;
  scope?: "metadata" | "thread" | string;
};

export type InboundError = {
  event: "error";
  chat_id?: string;
  detail?: string;
};

export type InboundEvent =
  | InboundMeta
  | InboundUserInput
  | InboundAgentMessage
  | InboundFileEdit
  | InboundDiagramEvent
  | InboundDelta
  | InboundStreamEnd
  | InboundReasoningDelta
  | InboundReasoningEnd
  | InboundRuntimeModel
  | InboundTurnEnd
  | InboundGoalStatus
  | InboundGoalState
  | InboundSessionUpdated
  | InboundError;

/** Base64-encoded image attached to an outbound ``message`` envelope.
 *
 * ``data_url`` must be a ``data:image/<png|jpeg|webp|gif>;base64,...`` string
 * — the server whitelists those MIME types and rejects everything else
 * (including SVG, to avoid an XSS surface). ``name`` is advisory: it's
 * preserved for the file on disk and surfaced as the placeholder label when
 * the session is replayed.
 */
export interface OutboundMedia {
  data_url: string;
  name?: string;
}

export interface OutboundImageGeneration {
  enabled: true;
  aspect_ratio?: string | null;
}

/** Response shape for ``GET .../webui-thread`` (server-built transcript replay). */
export interface WebuiThreadPersistedPayload {
  schemaVersion: number;
  sessionKey?: string;
  savedAt?: string;
  messages: UIMessage[];
}

export type Outbound =
  | { type: "new_chat" }
  | { type: "attach"; chat_id: string }
  | {
      type: "message";
      chat_id: string;
      content: string;
      media?: OutboundMedia[];
      image_generation?: OutboundImageGeneration;
      /** Marks messages sent by the embedded WebUI, without changing the
       * generic websocket protocol for other clients. */
      webui?: true;
    };

export interface WorkspaceProjectInfo {
  projectRoot: string;
  catbuddyDir: string;
  workspace: string;
}

export interface WorkspaceTreeNode {
  name: string;
  path: string;
  relativePath: string;
  isDirectory: boolean;
  isCatbuddyDir: boolean;
  children?: WorkspaceTreeNode[];
}
