export { BootstrapAuthRequired } from './errors'
export { requiresEmailLogin, requiresWebLogin } from './policy'
export { clearAuthToken, hasAuthToken, loadAuthToken, saveAuthToken } from './session'
export { requestEmailCode, verifyEmailCode } from './email-client'
export { loginWithPassword, registerWithPassword } from './password-client'
export type { AuthTokenResponse } from './password-client'
